# Configuration for the Modbus to OPC UA Gateway

modbus:
  ip: "127.0.0.1"
  port: 1502
  slave_id: 3
  timeout_sec: 5

opcua:
  port: 4840

security:
  username: "admin"
  password: "your_secure_password"

logging:
  file: "/var/log/modbus_gateway.log"
  # Log levels: 0=ERROR, 1=WARN, 2=INFO, 3=DEBUG
  level: 2

# Mappings from Modbus registers to OPC UA nodes
# The 'format' key specifies how to interpret the data.
# - FIXn: Decimal number with 'n' places. (e.g., FIX0, FIX2).
# - ENUM: An enumeration. 'enum_values' map must be provided.
# - FW: Firmware version string.
# - DT / TM: A specific point in time (DateTime).
# - Duration: A time interval.
# - TEMP: Temperature (handled as a float).
mappings:
  - name: "AC Active Power (Total)"
    modbus_address: 30775
    opcua_node_id: "sma.ac_power_total"
    data_type: "S32"
    format: "FIX0"
    poll_interval_ms: 2000

  - name: "Grid Frequency"
    modbus_address: 30803
    opcua_node_id: "sma.grid_frequency"
    data_type: "U32"
    format: "FIX2"
    poll_interval_ms: 2000

  - name: "Device Status"
    modbus_address: 30201
    opcua_node_id: "sma.device_status"
    data_type: "U32"
    format: "ENUM"
    poll_interval_ms: 5000
    enum_values:
      35: "Error"
      303: "Off"
      307: "OK"
      455: "Warning"
      
  - name: "Device Local Time"
    modbus_address: 30229
    opcua_node_id: "sma.device_time"
    data_type: "U32"
    format: "DT"
    poll_interval_ms: 60000

  - name: "Feed-in Time"
    modbus_address: 30525
    opcua_node_id: "sma.feed_in_time"
    data_type: "U64"
    format: "Duration"
    poll_interval_ms: 60000

  - name: "Total Yield"
    modbus_address: 30513
    opcua_node_id: "sma.total_yield"
    data_type: "U64"
    format: "FIX0"
    poll_interval_ms: 60000

  - name: "Software Package Version"
    modbus_address: 30059
    opcua_node_id: "sma.firmware_version"
    data_type: "U32"
    format: "FW"
    poll_interval_ms: 3600000

