# Configuration for the Modbus to OPC UA Gateway

modbus:
  ip: "127.0.0.1"
  port: 1502
  slave_id: 3
  timeout_sec: 5

opcua:
  port: 4840

security:
  username: "admin"
  # username: "" # uncomment to disable auth
  password: "your_secure_password"
  # password: "" # uncomment to disable password

logging:
  file: "/var/log/modbus_gateway.log"
  # Log levels: 0=DEBUG, 1=INFO, 2=WARN, 3=ERROR
  level: 1

# Mappings from Modbus registers to OPC UA nodes
mappings:
  - name: "AC Active Power (Total)"
    modbus_address: 30775
    opcua_node_id: "sma.ac_power_total"
    data_type: "S32"
    scale: 1.0
    poll_interval_ms: 2000

  - name: "Grid Frequency"
    modbus_address: 30803
    opcua_node_id: "sma.grid_frequency"
    data_type: "U32"
    scale: 0.01
    poll_interval_ms: 2000

  - name: "Daily Yield"
    modbus_address: 30517
    opcua_node_id: "sma.daily_yield"
    data_type: "U32"
    scale: 1.0
    poll_interval_ms: 15000

  - name: "Total Yield"
    modbus_address: 30513
    opcua_node_id: "sma.total_yield"
    data_type: "U32"
    scale: 1.0
    poll_interval_ms: 60000

  - name: "Device Status"
    modbus_address: 30201
    opcua_node_id: "sma.device_status"
    data_type: "U32" # ENUM type, raw value will be exposed
    scale: 1.0
    poll_interval_ms: 5000
